services:
  nextjs:
    container_name: merchant_on_boarding
    build:
      context: .
      args:
        NODE_ENV: production
        # JWT_SECRET: ${JWT_SECRET}
        # PROMO_ENGINE_API: ${PROMO_ENGINE_API}
    env_file:
      - .env.production
    ports:
      - "3003:3000"
    restart: unless-stopped
